config/routes.rb
Admintools::Application.routes.draw do

  devise_for :users, :path => 'teamleader'
  devise_for :admins, :path => 'admin'

  namespace :teamleader do
    root :to => 'dashboard#index'
    resources :absents
    resources :tasks
    match "/birthday" => "users#birthday", :as => 'birthday'
    get "/teamleader_users"=>"users#teamleader_users", :as=>:show_users
    resource :skills do
      get :show_list, :on => :member
    end
    get "skills/restore/:id" => "skills#restore", :as => :restore_skills
    delete "skills/delete/:id" => "skills#destroy", :as => :delete_skills

    resources :users, :except => [:new, :create, :destroy] do
      get "/skills" => "skills#show", :as => :skill_list_show
      resource :skills
      member do
        get :edit_password
        put :update_password
      end
    end
    resources :user_changes, :only => [:index, :show]
    resources :reports do
      member do
        put :teamleader_mail_send
      end
    end
    resources :poll
    get "departments/restore/:id" => "departments#restore", :as => :restore_department
    resources :departments
    resources :dashboard, :only => [:index]
    post 'poll/voted' => 'poll#voted', :as => 'voted'
    resources :rooms, :only => [:index]
    resource  :vacations, :except => [:index]
    resources :users do
      resources :time_requests, :only => [:index]
    end
    resources :time_requests, :except => [:show] do
      get :approve
      get :decline
      get :alternative
    end
    resources :material_requests, :except => :show do
      get :approve
      get :send_requests, :on => :collection
    end
  end

  namespace :admin do
    authenticate :admin do
      mount Resque::Server.new, :at => "/resque"
    end

    root :to => 'rooms#index'

    resources :devices
    resources :rooms
    resources :users do
      resource :skills, :only => [:show, :edit, :update]
    end
    resources :desktops
    resources :admins
    resources :constructors, :except => [:index, :show]
    resources :domains
    resources :internet_pings, :only => [:index]
    resources :events

    namespace :local_pings do
      resources :subnetworks, :only => [:new, :create, :destroy]
    end

    get "tasks"               => "tasks#index",           :as => :show_tasks
    put "tasks/workers"       => "tasks#start_workers",   :as => :start_workers
    put "tasks/scheduler"     => "tasks#start_scheduler", :as => :start_scheduler
    delete "tasks/workers"    => "tasks#stop_workers",    :as => :stop_workers
    delete "tasks/scheduler"  => "tasks#stop_scheduler",  :as => :stop_scheduler

    get "/sarg" => "sarg#index", :as =>  :sarg_index
    post "/sarg/folder_create" => "sarg#folder_create", :as =>  :sarg_folder_create

    get "rooms/:id/constructor" => "constructors#show", :as => :room_constructor

    get "events/new/:start/:end/:all_day" => "events#new"
    get "local_pings" => "local_pings#index", :as => :local_pings
    get  "local_pings/import" => "local_pings#import", :as => :import_local_pings
    delete "local_pings" => "local_pings#clear", :as => :clear_local_logs

    get  "internet_pings/import" => "internet_pings#import", :as => :import_server_pings
    delete "internet_pings" => "internet_pings#clear", :as => :clear_server_logs

    get "users/restore/:id"     => "users#restore", :as => :restore_user
    get "admins/restore/:id"     => "admins#restore", :as => :restore_admin

    constraints(:ip => /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/) do
      get "local_pings/:ip" => "local_pings#show", :as => :local_ping
    end
  end

  root :to => 'teamleader/users#index'
end

app/models/desktop.rb
class Desktop < ActiveRecord::Base
  self.per_page = 10
  before_save lambda{ self.mac.upcase! }
  after_save :re_counter
  has_many :ping_logs, :as => :ping
  belongs_to :room, :counter_cache => true
  belongs_to :user
  has_one :workplace # , :dependent => :nullify
  validates :ip,  :presence => true, :uniqueness => true, :format => {:with => /\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/, :massage => 'Wrong IP'}
  validates :mac, :presence => true, :uniqueness => true, :format => {:with => /\b([A-Fa-f0-9]{2}[:-]){5}[A-Fa-f0-9]{2}\b/, :massage => 'Wrong MAC'}
  validates :user_id, :uniqueness => true, :if => :user_id?
  validates :name, :presence => true
  private
  def re_counter
    Room.all.each do |r|
      Room.update r.id, :desktops_count => r.desktops.count
    end
  end
end

app/controllers/admin/desktops_controller.rb
class Admin::DesktopsController < Admin::AppAdminController
  before_filter :all_users_and_rooms, :only => [:index, :new, :edit, :create, :update]
  before_filter :current_desktop, :only => [:show, :edit, :update, :destroy]

  def index
    @search = Desktop.search(params[:search] || {"meta_sort" => "id.asc"})
    @desktops = @search.includes(:user, :room).paginate(:page => params[:page]).order('created_at').all
  end

  def new
    @desktop = Desktop.new
  end

  def show
  end

  def edit
  end

  def create
    @desktop = Desktop.new(params[:desktop])
    if @desktop.save
      redirect_to :admin_desktops, :notice => t(:'admin.desktops.create.created', :name => @desktop.name)
    else
      render :action => "new"
    end
  end

  def update
    if @desktop.update_attributes(params[:desktop])
      redirect_to :admin_desktops, :notice => t(:'admin.desktops.update.updated', :name => @desktop.name)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @desktop.destroy and redirect_to :admin_desktops, :notice => t(:'admin.desktops.destroy.destroyed', :name => @desktop.name)
  end

  private
  def all_users_and_rooms
    @users ||= User.all
    @rooms ||= Room.all
  end

  def current_desktop
    @desktop = Desktop.find_by_id(params[:id])
  end
end

app/views/admin/desktops/_form.html.haml
= form_for([:admin, @desktop], :html => {:class => 'well form-horizontal'}) do |f|
  -if @desktop.errors.any?
    #error_explanation.alert.alert-error
      %a.close{"data-dismiss" => "alert", :href => "#"}
        ×
      %h2 Возникли ошибки:
      %ul
        - @desktop.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    .control-group
      = f.label :name, 'Имя ПК', :class => 'control-label'
      .controls
        = f.text_field :name, :class => 'input-xlarge'
    .control-group
      = f.label :ip, 'IP', :class => 'control-label'
      .controls
        = f.text_field :ip, :class => 'input-xlarge'
    .control-group
      = f.label :mac, 'MAC', :class => 'control-label'
      .controls
        = f.text_field :mac, :class => 'input-xlarge'
    .control-group
      = f.label :user_id, 'Пользователь', :class => 'control-label'
      .controls
        = select_tag :user_id, options_from_collection_for_select(@users, :id, :full_name, @desktop.user_id), :prompt => 'Выбрать пользователя', :class => 'input-xlarge', :name => "desktop[user_id]"
    .control-group
      = f.label :room_id, 'Офис', :class => 'control-label'
      .controls
        = select_tag :room_id, options_from_collection_for_select(@rooms, :id, :name, @desktop.room_id), :prompt => 'Выбрать офис', :class => 'input-xlarge', :name => "desktop[room_id]"
    .control-group
      = f.label :info, 'Информация', :class => 'control-label'
      .controls
        = f.text_area :info, :id => 'nic', :class => 'input-xxlarge', :style => 'height:200px'
    .form-actions
      = f.submit (@desktop.id?) ? 'Изменить' : 'Создать' , :class => 'btn btn-primary'
      = link_to 'Назад', admin_desktops_path, :class => 'btn'

app/views/admin/desktops/_sidebar.html.haml
= form_for [:admin, @search], :url => admin_desktops_path, :html => {:method => :get, :class => 'well form-horizontal'} do |f|
  .search-query{:type => "text"}
    %p
      = f.label :name_equals, "Введите имя компьютера"
      = f.text_field :name_equals
    %p
      = f.label :ip_equals, "Введите ip"
      = f.text_field :ip_equals
    %p
      = f.label :mac_equals, "Введите mac"
      = f.text_field :mac_equals
    %p
      = f.label :user_id_equals, "Выберите пользователя"
      = select_tag :user_id_equals, options_from_collection_for_select(@users, :id, :full_name), :prompt => 'Выбрать пользователя', :include_blank => true, :name => "search[user_id_equals]"
    %p
      = f.label :room_id_equals, "Выберите офис"
      = select_tag :room_id_equals, options_from_collection_for_select(@rooms, :id, :name), :prompt => 'Выбрать офис', :include_blank => true, :name => "search[room_id_equals]"
    %button.btn{:type => "submit"} Найти
    = link_to "Сбросить", admin_desktops_path, :class => 'btn btn-inverse'

app/views/admin/desktops/edit.html.haml
%h1 Редактировать ПК

%hr

= render 'form'

app/views/admin/desktops/index.html.haml
%h1 Компьютеры

%hr

.well
  %table.table.table-striped.pretty
    %thead
      %tr
        %th= sort_link @search, :name, "Имя ПК"
        %th= sort_link @search, :ip, "IP"
        %th= sort_link @search, :mac, "MAC"
        %th Офис
        %th= sort_link @search, :user_id, "Пользователь"
        %th
          = link_to new_admin_desktop_path, :class => "btn btn-success" do
            %i.icon-plus
            Создать
    %tbody
      - @desktops.each do |desktop|
        %tr
          %td= desktop.name
          %td= link_to desktop.ip, admin_local_pings_path(desktop.ip)
          %td= desktop.mac
          %td= check_empty(desktop.room, "name")
          %td= check_empty(desktop.user, "full_name")
          %td
            = link_to admin_desktop_path(desktop), :class => "btn" do
              %i.icon-zoom-in
              Просмотр
            = link_to edit_admin_desktop_path(desktop), :class => "btn" do
              %i.icon-pencil
              Редактировать
            = link_to admin_desktop_path(desktop), :method => :DELETE, :class => "btn btn-danger", :confirm => "Ты уверен?" do
              %i.icon-remove
              Удалить

- content_for :sidebar, render(:partial => 'sidebar')

= will_paginate @desktops,:class=>"pagination pagination-centered"

app/views/admin/desktops/new.html.haml
%h1 Добавить ПК

%hr

= render 'form'

app/views/admin/desktops/show.html.haml
%h1= t :'.title', :name => @desktop.name

%hr

.well.form-horizontal
  %fieldset
    .control-group
      %label.control-label
        Имя ПК
      .controls
        %span.input-xlarge.uneditable-input= @desktop.name
    .control-group
      %label.control-label
        IP
      .controls
        %span.input-xlarge.uneditable-input= @desktop.ip
    .control-group
      %label.control-label
        MAC
      .controls
        %span.input-xlarge.uneditable-input= @desktop.mac
    .control-group
      %label.control-label
        Офис
      .controls
        %span.input-xlarge.uneditable-input
          = (@desktop.room_id) ? (@desktop.room.name) : ('-')
    .control-group
      %label.control-label
        Пользователь
      .controls
        %span.input-xlarge.uneditable-input
          = (@desktop.user_id) ? (@desktop.user.full_name) : ('-')
    .control-group
      %label.control-label
        Информация
      .controls
        %span.input-xxlarge{:readonly => 'readonly', :style => 'height:200px;overflow:auto'}= @desktop.info.html_safe
    .form-actions
      = link_to admin_desktops_path, :class => 'btn btn-primary' do
        %i.icon-circle-arrow-left
        Назад
      = link_to edit_admin_desktop_path, :class => 'btn btn-warning' do
        %i.icon-pencil
        Редактировать