config/routes.rb
Admintools::Application.routes.draw do

  devise_for :users, :path => 'teamleader'
  devise_for :admins, :path => 'admin'

  namespace :teamleader do
    root :to => 'dashboard#index'
    resources :absents
    resources :tasks
    match "/birthday" => "users#birthday", :as => 'birthday'
    get "/teamleader_users"=>"users#teamleader_users", :as=>:show_users
    resource :skills do
      get :show_list, :on => :member
    end
    get "skills/restore/:id" => "skills#restore", :as => :restore_skills
    delete "skills/delete/:id" => "skills#destroy", :as => :delete_skills

    resources :users, :except => [:new, :create, :destroy] do
      get "/skills" => "skills#show", :as => :skill_list_show
      resource :skills
      member do
        get :edit_password
        put :update_password
      end
    end
    resources :user_changes, :only => [:index, :show]
    resources :reports do
      member do
        put :teamleader_mail_send
      end
    end
    resources :poll
    get "departments/restore/:id" => "departments#restore", :as => :restore_department
    resources :departments
    resources :dashboard, :only => [:index]
    post 'poll/voted' => 'poll#voted', :as => 'voted'
    resources :rooms, :only => [:index]
    resource  :vacations, :except => [:index]
    resources :users do
      resources :time_requests, :only => [:index]
    end
    resources :time_requests, :except => [:show] do
      get :approve
      get :decline
      get :alternative
    end
    resources :material_requests, :except => :show do
      get :approve
      get :send_requests, :on => :collection
    end
  end

  namespace :admin do
    authenticate :admin do
      mount Resque::Server.new, :at => "/resque"
    end

    root :to => 'rooms#index'

    resources :devices
    resources :rooms
    resources :users do
      resource :skills, :only => [:show, :edit, :update]
    end
    resources :desktops
    resources :admins
    resources :constructors, :except => [:index, :show]
    resources :domains
    resources :internet_pings, :only => [:index]
    resources :events

    namespace :local_pings do
      resources :subnetworks, :only => [:new, :create, :destroy]
    end

    get "tasks"               => "tasks#index",           :as => :show_tasks
    put "tasks/workers"       => "tasks#start_workers",   :as => :start_workers
    put "tasks/scheduler"     => "tasks#start_scheduler", :as => :start_scheduler
    delete "tasks/workers"    => "tasks#stop_workers",    :as => :stop_workers
    delete "tasks/scheduler"  => "tasks#stop_scheduler",  :as => :stop_scheduler

    get "/sarg" => "sarg#index", :as =>  :sarg_index
    post "/sarg/folder_create" => "sarg#folder_create", :as =>  :sarg_folder_create

    get "rooms/:id/constructor" => "constructors#show", :as => :room_constructor

    get "events/new/:start/:end/:all_day" => "events#new"
    get "local_pings" => "local_pings#index", :as => :local_pings
    get  "local_pings/import" => "local_pings#import", :as => :import_local_pings
    delete "local_pings" => "local_pings#clear", :as => :clear_local_logs

    get  "internet_pings/import" => "internet_pings#import", :as => :import_server_pings
    delete "internet_pings" => "internet_pings#clear", :as => :clear_server_logs

    get "users/restore/:id"     => "users#restore", :as => :restore_user
    get "admins/restore/:id"     => "admins#restore", :as => :restore_admin

    constraints(:ip => /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/) do
      get "local_pings/:ip" => "local_pings#show", :as => :local_ping
    end
  end

  root :to => 'teamleader/users#index'
end

app/views/admin/admins/_form.html.haml
= form_for([:admin, @admin], :html => {:class => 'well form-horizontal', :multipart => true}) do |a|
  -if @admin.errors.any?
    #error_explanation.alert.alert-error
      %a.close{"data-dismiss" => "alert", :href => "#"}
        ×
      %h2 Возникли ошибки:
      %ul
        - @admin.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    .control-group
      = a.label :email, 'Email', :class => 'control-label'
      .controls
        = a.text_field :email, :class => 'input-xlarge'
    .control-group
      = a.label :name, 'Имя', :class => 'control-label'
      .controls
        = a.text_field :name, :class => 'input-xlarge'
    .control-group
      = a.label :password, 'Пароль', :class => 'control-label'
      .controls
        = a.password_field :password, :class => 'input-xlarge'
    .control-group
      = a.label :password_confirmation, 'Подтверждение', :class => 'control-label'
      .controls
        = a.password_field :password_confirmation, :class => 'input-xlarge'
    .form-actions
      = a.submit (@admin.id?) ? 'Изменить' : 'Создать' , :class => 'btn btn-primary'
      = link_to 'Назад', admin_admins_path, :class => 'btn'

app/views/admin/admins/_sidebar.html.haml
= form_for @search, :url => admin_admins_path, :html => {:method => :get, :class => 'well form-horizontal'} do |f|
  .search-query{:type => "text"}
    %p
      = f.label :name_equals, "Введите имя"
      = f.text_field :name_equals
    %p
      = f.label :email_equals, "Введите email"
      = f.text_field :email_equals
    %button.btn{:type => "submit"} Найти
    = link_to "Сбросить", admin_admins_path, :class => 'btn btn-inverse'

app/views/admin/admins/edit.html.haml
%h1 Изменить пользователя

%hr

= render 'form'

app/views/admin/admins/index.html.haml
%h1
  Администраторы

  .pull-right
    -if @deleted!="1"
      .users_real
        = link_to 'Удаленные', admin_admins_path(:deleted => 1), :class => "btn btn-danger", :id => "deleted_admins", "data-loading-text" => "???"
      .users_deleted.hide
        = link_to 'Действующие', admin_admins_path(:deleted => 0), :class => "btn btn-success", :id => "real_admins", "data-loading-text" => "???"
    -else
      .users_real.hide
        = link_to 'Удаленные', admin_admins_path(:deleted => 1), :class => "btn btn-danger", :id => "deleted_admins", "data-loading-text" => "???"
      .users_deleted
        = link_to 'Действующие', admin_admins_path(:deleted => 0), :class => "btn btn-success", :id => "real_admins", "data-loading-text" => "???"

%hr

.well
  %table.table.table-striped.pretty
    %thead
      %tr
        %th= sort_link @search, :name, "Admin name"
        %th= sort_link @search, :email, "Email"
        %th
          -if @deleted!="1"
            = link_to new_admin_admin_path, :class => "btn btn-success", :id => "creating_new_admin" do
              %i.icon-plus
              Создать
    %tbody
      - @admins.each do |admin|
        %tr
          %td= admin.name
          %td= admin.email
          %td
            -if @deleted!="1"
              .btn-group
                = link_to admin_admin_path(admin), :class => "btn" do
                  %i.icon-zoom-in
                  Просмотр
                = link_to edit_admin_admin_path(admin), :class => "btn", :confirm => "Ты уверен?" do
                  %i.icon-pencil
                  Редактировать
                = link_to admin_admin_path(admin), :method => :DELETE, :class => "btn btn-danger", :confirm => "Ты уверен?" do
                  %i.icon-remove
                  Удалить
            -else
              = link_to admin_restore_admin_path(admin), :class => "btn btn-success" do
                %i.icon-plus
                Восстановить

- content_for :sidebar, render(:partial => 'sidebar')

= will_paginate @admins,:class=>"pagination pagination-centered"

app/views/admin/admins/new.html.haml
%h1 Добавить администратора

%hr

= render 'form'

app/views/admin/admins/show.html.haml
%h1 Информация пользователя

%hr

-if @admin
  .well.form-horizontal
    %fieldset
      .control-group
        %label.control-label
          Email
        .controls
          %span.input-xlarge.uneditable-input= @admin.email
      .control-group
        %label.control-label
          Admin name
        .controls
          %span.input-xlarge.uneditable-input= @admin.name
      .form-actions
        = link_to admin_admins_path, :class => 'btn btn-primary' do
          %i.icon-circle-arrow-left
          Назад
        = link_to edit_admin_admin_path, :class => 'btn btn-warning' do
          %i.icon-pencil
          Редактировать