config/routes.rb
Admintools::Application.routes.draw do

  devise_for :users, :path => 'teamleader'
  devise_for :admins, :path => 'admin'

  namespace :teamleader do
    root :to => 'dashboard#index'
    resources :absents
    resources :tasks
    match "/birthday" => "users#birthday", :as => 'birthday'
    get "/teamleader_users"=>"users#teamleader_users", :as=>:show_users
    resource :skills do
      get :show_list, :on => :member
    end
    get "skills/restore/:id" => "skills#restore", :as => :restore_skills
    delete "skills/delete/:id" => "skills#destroy", :as => :delete_skills

    resources :users, :except => [:new, :create, :destroy] do
      get "/skills" => "skills#show", :as => :skill_list_show
      resource :skills
      member do
        get :edit_password
        put :update_password
      end
    end
    resources :user_changes, :only => [:index, :show]
    resources :reports do
      member do
        put :teamleader_mail_send
      end
    end
    resources :poll
    get "departments/restore/:id" => "departments#restore", :as => :restore_department
    resources :departments
    resources :dashboard, :only => [:index]
    post 'poll/voted' => 'poll#voted', :as => 'voted'
    resources :rooms, :only => [:index]
    resource  :vacations, :except => [:index]
    resources :users do
      resources :time_requests, :only => [:index]
    end
    resources :time_requests, :except => [:show] do
      get :approve
      get :decline
      get :alternative
    end
    resources :material_requests, :except => :show do
      get :approve
      get :send_requests, :on => :collection
    end
  end

  namespace :admin do
    authenticate :admin do
      mount Resque::Server.new, :at => "/resque"
    end

    root :to => 'rooms#index'

    resources :devices
    resources :rooms
    resources :users do
      resource :skills, :only => [:show, :edit, :update]
    end
    resources :desktops
    resources :admins
    resources :constructors, :except => [:index, :show]
    resources :domains
    resources :internet_pings, :only => [:index]
    resources :events

    namespace :local_pings do
      resources :subnetworks, :only => [:new, :create, :destroy]
    end

    get "tasks"               => "tasks#index",           :as => :show_tasks
    put "tasks/workers"       => "tasks#start_workers",   :as => :start_workers
    put "tasks/scheduler"     => "tasks#start_scheduler", :as => :start_scheduler
    delete "tasks/workers"    => "tasks#stop_workers",    :as => :stop_workers
    delete "tasks/scheduler"  => "tasks#stop_scheduler",  :as => :stop_scheduler

    get "/sarg" => "sarg#index", :as =>  :sarg_index
    post "/sarg/folder_create" => "sarg#folder_create", :as =>  :sarg_folder_create

    get "rooms/:id/constructor" => "constructors#show", :as => :room_constructor

    get "events/new/:start/:end/:all_day" => "events#new"
    get "local_pings" => "local_pings#index", :as => :local_pings
    get  "local_pings/import" => "local_pings#import", :as => :import_local_pings
    delete "local_pings" => "local_pings#clear", :as => :clear_local_logs

    get  "internet_pings/import" => "internet_pings#import", :as => :import_server_pings
    delete "internet_pings" => "internet_pings#clear", :as => :clear_server_logs

    get "users/restore/:id"     => "users#restore", :as => :restore_user
    get "admins/restore/:id"     => "admins#restore", :as => :restore_admin

    constraints(:ip => /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/) do
      get "local_pings/:ip" => "local_pings#show", :as => :local_ping
    end
  end

  root :to => 'teamleader/users#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
         # :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :recoverable,:authentication_keys => [ :email ]
  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_protected :role, :as => :user
  attr_accessor :changer

  acts_as_paranoid

  before_update :write_log
  before_update :toggle_out_of_work

  self.per_page = 10

  has_many :time_requests, :dependent => :destroy
  has_many :approved_time_requests, :conditions => {:approved => true}
  has_many :not_approved_time_requests, :conditions => {:approved => false}

  has_one  :desktop

  has_many :devices

  has_many :voteds

  has_many :absents

  has_many :users_change, :as => :editor, :class_name => 'UserChange'

  has_many :user_changes, :foreign_key => "edited_id"

  has_many :skill_user_relations, :dependent => :destroy

  has_many :skills, :through => :skill_user_relations

  has_one :room, :through => :desktop

  has_many :tasks

  # self join
  has_many :subordinates, :class_name => "User", :foreign_key => "manager_id"
  belongs_to :manager, :class_name => "User"

  belongs_to :department

  has_many :reports

  has_many :polls

  has_many :relationships, foreign_key: 'manager_id', dependent: :destroy
  has_many :managed_users, through: :relationships, source: :managed
  has_many :reverse_relationships, foreign_key: 'managed_id',
           class_name:  'Relationship',
           dependent:   :destroy
  has_many :user_managers, through: :reverse_relationships, source: :manager
  has_many :vacations, :dependent => :destroy
  has_many :material_requests

  validates :first_name,    :presence => true
  validates :last_name,     :presence => true
  validates :skype,         :presence => true

  validates :birthday,      :if => :by_user,
                            :presence => true,
                            :format => { :with => /\d{4}\-\d{2}\-\d{2}/ }
  validates :daily_1, :daily_2,
            :daily_3, :daily_4,
            :daily_5,       :if => :by_user,
                            :presence => true,
                            :format => { :with => /^\d{2}\:\d{2}\-\d{2}\:\d{2}$/ }

  validates :department_id, :numericality => { :greater_than => 0 },
                            :if => :department_id?

  validates :role,          :uniqueness => { :scope => :department_id, :message => :one_leader },
                            :if => :set_teamleader


  ROLES = %w[user teamleader manager admin]

  scope :by_name, lambda { order(:last_name, :first_name) }
  scope :managers, lambda { where(:role => ['manager']) }
  scope :admins, lambda { where(:role => ['admin']) }
  scope :out_department, lambda { where(:department_id => nil, :role => [:user, :teamleader]) }
  scope :for_manager, lambda { where(:role => ['teamleader', 'user']).order(:last_name, :first_name) }
  scope :teamleader_users, lambda { |u| where(:role => 'user', :department_id => u.department_id).order(:last_name, :first_name) }
  scope :user_teamleader, lambda {|u| where(:role =>'teamleader',:department_id => u.department_id).order(:last_name,:first_name) }
  scope :two_week_birthday, lambda {where("birthday < ? and birthday >= ?", Time.now.to_date+14.days,Time.now.to_date).order("birthday ASC")}

  scope :out_of_work, where("`users`.`employer` = ''")

  def vacation_data(curr_user)
    {
      name: self.full_name,
      desc: "",
      values:
        self.vacations.by_year(Date.today.year).map {|vacation|
          {
            from: "/Date(\"#{vacation.date_from.strftime('%m/%d/%Y')}\")/",
            to: "/Date(\"#{vacation.date_to.strftime("%m/%d/%Y")}\")/",
            label: "",
            customClass: "gantt#{vacation.approved ? "Green" : "Red"} #{"acceptable" if curr_user.is_admin? && !vacation.approved } #{"editable" if vacation.date_to > Date.today && self.id == curr_user.id} #{"removable" if vacation.date_from > Date.today && self.id == curr_user.id}",
            dataObj: {id: vacation.id, from: vacation.date_from, to: vacation.date_to}
          }
        }
    }
  end

  def is_user?
    self.role.eql?'user'
  end

  def is_admin?
    self.role.eql?'admin'
  end

  def is_manager?
    self.role.eql?'manager'
  end

  def is_teamleader?
    self.role.eql?'teamleader'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def formatted_birthday
    self.birthday.blank? ? "" : I18n.l(self.birthday, :format => :birthday)
  end

  def self.subordinates(collect, user)
    collect.where(:users => {:role => 'user', :department_id => user.department_id})
  end

  def manage! manager_id
    reverse_relationships.create!(manager_id: manager_id)
  end

  def unmanage! manager_id
    reverse_relationships.find_by_manager_id(manager_id).destroy
  end

  private

  def set_teamleader
    self.is_teamleader?
  end

  def by_user
    self.changer.is_a?User
  end

  def write_log
    UserChange.create(:editor => self.changer,
                      :edited_id => self.id,
                      :change => self.changes) if(self.changer && self.changed?)
  end

  def toggle_out_of_work
    if self.changes.has_key?(:employer)
      if self.changes[:employer][0].present? && self.changes[:employer][1].blank?
        self.out_of_work = Time.zone.now
      end
      if self.changes[:employer][0].blank? && self.changes[:employer][1].present?
        self.out_of_work = nil
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AppAdminController

  before_filter :current_user, :only => [:show, :edit, :create, :update, :destroy]
  before_filter :get_managers, :only => [:new, :create, :edit, :update]

  respond_to :js, :html

  def index
    @deleted = params[:deleted]
    if @deleted=="1"
      @search = User.only_deleted.search(params[:search] || {"meta_sort" => "id.asc"})
    else
      @search = User.search(params[:search] || {"meta_sort" => "id.asc"})
    end
    @users = @search.includes(:desktop, :room).paginate(:page => params[:page]).order('created_at').all
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end

  def create
    @user = User.new(params[:user])
    @user.password = @user.password_confirmation = :'123456'
    if @user.save
      AdminMailer.send_email_to_the_added_user(@user).deliver
      redirect_to :admin_users, :notice => t('admin.users.create.created', full_name: @user.full_name)
    else
      render :action => 'new'
    end
  end

  def update
    params[:user].update(:changer => current_admin)
    if @user.update_attributes(params[:user])
      redirect_to :admin_users, :notice => t('admin.users.update.updated')
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user.destroy and redirect_to :admin_users, :notice => t('admin.users.destroy.destroyed', :full_name => @user.full_name)
  end

  def restore
    user = User.only_deleted.find_by_id(params[:id])
    user.update_attributes(:deleted_at => nil)
    redirect_to admin_users_path(:deleted => 1), :notice => t('admin.users.restore.restored', :full_name => user.full_name)
  end

  private

  def current_user
    @user = User.find_by_id(params[:id])
  end

  def get_managers
    @managers = User.managers
    @departments = Department.all
  end
end

app/controllers/teamleader/users_controller.rb
class Teamleader::UsersController < Teamleader::AppTeamleaderController
  before_filter :init_user, :only => [:index, :show, :update, :destroy]
  before_filter :password_for_user, :only => [:edit_password, :update_password]
  before_filter :select_related_options, :only => [:edit, :update]
  before_filter :show_skills_button, :only => [:index, :show]


  def index
    @user_managers = @user.user_managers
    render 'show'
  end

  def show
    @user_managers = @user.user_managers
    @skills_button =  (((User.teamleader_users(current_user).include? @user) && (current_user.is_teamleader?)) || current_user.is_manager? || current_user.id == @user.id) && !@user.is_manager?
    i = 5
  end

  def teamleader_users
    authorize! :look, :teamleader_users
    @teamlead_bool=true if current_user.is_teamleader?
    @search = User.where(:department_id=>current_user.department_id).search(params[:search] || {"meta_sort" => "id.asc"})
    @users=@search.includes(:desktop, :room).paginate(:page => params[:page]).order('created_at').all
  end

  def edit
    @user = User.find(params[:id])
    authorize! :manage, @user
    @user_managers = @user.user_manager_ids
    @managers = User.managers
  end

  def update
    list_managers = params[:ch_managers]||[].map(&:to_i)
    new_managers = list_managers - @user.user_manager_ids
    past_managers = @user.user_manager_ids - list_managers
    past_managers.each {|manager| @user.unmanage! manager }
    new_managers.each {|manager| @user.manage! manager }

    params[:user].update(:changer => current_user)
    if @user.update_attributes(params[:user], :as => :user)
      redirect_to :teamleader_user, :notice => t(:'teamleader.users.update.updated')
    else
      render :action => 'edit'
    end
  end

  def birthday
    @users = {}
    users = User.where('birthday IS NOT NULL AND birthday!="0000-00-00"').sort_by{ |d| d.birthday.day }
    Date::MONTHNAMES[1..-1].each do |month|
      @users[month] = users.select{ |u| u.birthday.strftime("%B") == month }
    end
  end

  def edit_password
  end

  def update_password
    params[:user].select! { |k,v| k.in? %w`current_password password password_confirmation` }
    if @user.update_with_password(params[:user])
      sign_in(@user, :bypass => true)
      redirect_to root_path, notice: t(:'teamleader.users.update_password.updated')
    else
      render 'edit_password'
    end
  end

  def manage
    @user = User.find params[:id]
    current_user.manage! @user
  end

  def unmanage
    @user = User.find params[:id]
    current_user.unmanage! @user
  end

  private
  def init_user
    if params[:id]
      @user = User.find_by_id(params[:id])
    else
      @user = current_user
    end
  end

  def password_for_user
    @user = current_user
  end

  def select_related_options
    @departments = Department.all
    @managers = User.managers
  end

  def show_skills_button
    @skills_button =  (((User.teamleader_users(current_user).include? @user) && (current_user.is_teamleader?)) ||
                           current_user.is_manager? || current_user.id == @user.id) && !@user.is_manager?
  end

end

app/views/admin/users/_form.html.haml
= form_for([:admin, @user], :html => {:class => 'well form-horizontal', :multipart => true}) do |u|
  -if @user.errors.any?
    #error_explanation.alert.alert-error
      %a.close{"data-dismiss" => "alert", :href => "#"}
        ×
      %h2 Возникли ошибки:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    .control-group
      = u.label :first_name, 'Имя', :class => 'control-label'
      .controls
        = u.text_field :first_name, :class => 'input-xlarge'
    .control-group
      = u.label :last_name, 'Фамилия', :class => 'control-label'
      .controls
        = u.text_field :last_name, :class => 'input-xlarge'
    .control-group
      = u.label :role, 'Роль', :class => 'control-label'
      .controls
        / = u.select :role, {:'пользователь' => :user, :'менеджер' => :manager, :'тимлид' => :teamleader}, {:selected => :user},  :class => 'input-xlarge'
        = u.select :role, User::ROLES, {}, :class => 'input-xlarge'
    .control-group
      = u.label :department_id, 'Отдел', :class => 'control-label'
      .controls
        = u.collection_select :department_id, @departments, :id, :name, {:include_blank => '---'}, :class => 'input-xlarge'
    .control-group
      = u.label :email, 'Email', :class => 'control-label'
      .controls
        = u.text_field :email, :class => 'input-xlarge'
    .control-group
      = u.label :phone_field, 'Телефон', :class => 'control-label'
      .controls
        = u.text_field :phone, :value => "#{@user.phone ||'+3 80'}", :class => 'input-xlarge'
    .control-group
      = u.label :skype, 'Skype', :class => 'control-label'
      .controls
        = u.text_field :skype, :class => 'input-xlarge'
        .control-group
    /   = u.label :birthday, 'Дата рождения', :class => 'control-label'
    /   .controls
    /     = u.text_field :birthday, :class => 'input-xlarge'
    -#.control-group
    -#  = u.label :daily, 'График работы', :class => 'control-label'
    -#  %br
    -#  .controls
    -#    -(0..6).to_a.map do |i|
    -#      %span{:style => "width:100px; display: inline-block;"}= Date::DAYNAMES[i]
    -#      = u.hidden_field "daily_#{i}".to_sym
    -#      - daily_vals = @user.send("daily_#{i}").split('-')
    -#      = text_field_tag nil, daily_vals.first, :class => 'input-small daily-from', "data-parent" => "#user_daily_#{i}"
    -#      = text_field_tag nil, daily_vals.last, :class => 'input-small daily-to', "data-parent" => "#user_daily_#{i}"
    -#      %br
    -#= u.hidden_field :daily
    -#= text_field_tag nil, nil, :class => 'input-small', :id => 'daily-from'
    -#= text_field_tag nil, nil, :class => 'input-small', :id => 'daily-to'
    / .control-group
    /   = label :manager_id, 'Менеджер', :class => 'control-label'
    /   .controls
    /     = u.collection_select :manager_id, @managers, :id, :full_name, {:include_blank => '---'}, :class => 'input-xlarge'
    / .control-group
    /   = u.label :employer, 'Заказчик', :class => 'control-label'
    /   .controls
    /     = u.text_field :employer, :class => 'input-xlarge'
    / .control-group
    /   = u.label :odesk, 'oDesk аккаунт', :class => 'control-label'
    /   .controls
    /     = u.url_field :odesk, :class => 'input-xlarge'
    .control-group
      = u.label :info, 'Информация', :class => 'control-label'
      .controls
        = u.text_area :info, :class => 'input-xxlarge', :id => 'nic', :style => "height:200px"
    .form-actions
      = u.submit (@user.id?) ? 'Изменить' : 'Создать' , :class => 'btn btn-primary'
      = link_to 'Назад', admin_users_path, :class => 'btn'

app/views/admin/users/_sidebar.html.haml
= form_for [:admin, @search], :url => admin_users_path, :html => {:method => :get, :class => 'well form-horizontal'} do |f|
  .search-query{:type => "text"}
    %p
      = f.label :first_name_equals, "Введите имя"
      = f.text_field :first_name_equals
    %p
      = f.label :last_name_equals, "Введите фамилию"
      = f.text_field :last_name_equals
    %p
      = f.label :email_equals, "Введите email"
      = f.text_field :email_equals
    %p
      = f.label :skype_equals, "Введите skype"
      = f.text_field :skype_equals
    %button.btn{:type => "submit"} Найти
    = link_to "Сбросить", admin_users_path, :class => 'btn btn-inverse'

app/views/admin/users/_users_data.html.haml
#select_users
  %table.table.table-striped.pretty
    %thead
      %tr
        %th Фото
        %th= sort_link @search, :first_name, "Имя"
        %th= sort_link @search, :last_name, "Фамилия"
        %th= sort_link @search, :role, "Роль"
        %th= sort_link @search, :phone, "Телефон"
        %th= sort_link @search, :email, "Email"
        %th= sort_link @search, :skype, "Skype"
        %th Офис
        %th
          -if @deleted!="1"
            = link_to new_admin_user_path, :class => "btn btn-success" do
              %i.icon-plus
              Создать
    %tbody
      - @users.each do |user|
        %tr
          %td= avatar_image_link_tag(user)
          %td= user.first_name
          %td= user.last_name
          %td= user.role
          %td= check_empty(user, "phone")
          %td= user.email
          %td= user.skype
          %td= check_empty(user.room, "name")
          %td
            -if @deleted!="1"
              .btn-group
                = link_to admin_user_path(user), :class => "btn btn-primary", :id => "user_profile" do
                  %i.icon-user
                  Профиль
                  = link_to '#', :class => "btn btn-primary dropdown-toggle", :'data-toggle' => "dropdown" do
                    %span.caret
                  %ul.dropdown-menu
                    %li
                      = link_to edit_admin_user_path(user) do
                        %i.icon-pencil
                        Редактировать
                    %li
                      = link_to admin_user_path(user), :method => :DELETE, :confirm => "Ты уверен?" do
                        %i.icon-trash
                        Уволить
              / = link_to admin_user_path(user), :class => "btn" do
              /   %i.icon-zoom-in
              /   Просмотр
              / = link_to edit_admin_user_path(user), :class => "btn" do
              /   %i.icon-pencil
              /   Редактировать
              / = link_to admin_user_path(user), :method => :DELETE, :class => "btn btn-danger", :confirm => "Ты уверен?" do
              /   %i.icon-remove
              /   Удалить
            -else
              = link_to admin_restore_user_path(user), :class => "btn btn-success" do
                %i.icon-plus
                Восстановить
  = will_paginate @users, :class=>"pagination pagination-centered"

app/views/admin/users/edit.html.haml
%h1 Редактировать пользователя

%hr

= render 'form'

app/views/admin/users/index.html.haml
%h1
  Пользователи
  .pull-right
    -if @deleted!="1"
      .users_real
        = link_to 'Уволенные', admin_users_path(:deleted => 1), :class => "btn btn-danger", :id => "deleted_users", "data-loading-text" => "???"
      .users_deleted.hide
        = link_to 'Действующие', admin_users_path(:deleted => 0), :class => "btn btn-success", :id => "real_users", "data-loading-text" => "???"
    -else
      .users_real.hide
        = link_to 'Уволенные', admin_users_path(:deleted => 1), :class => "btn btn-danger", :id => "deleted_users", "data-loading-text" => "???"
      .users_deleted
        = link_to 'Действующие', admin_users_path(:deleted => 0), :class => "btn btn-success", :id => "real_users", "data-loading-text" => "???"
.well
  = render 'users_data'
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/users/index.js.haml
$('#select_users').replaceWith('#{escape_javascript(render 'users_data')}')

app/views/admin/users/new.html.haml
%h1= t :'.title'

%hr

= render 'form'

app/views/admin/users/show.html.haml
%h1= t(:'.title', full_name: @user.full_name)

%hr

-if @user
  .well.form-horizontal
    %fieldset
      .control-group
        %label.control-label
          Фото
        .controls
          = avatar_image_link_tag(@user, 200)
    .control-group
      %label.control-label
        Имя
      .controls
        %span.input-xlarge.uneditable-input= @user.full_name
    .control-group
      %label.control-label
        Роль
      .controls
        %span.input-xlarge.uneditable-input= @user.role
    .control-group
      %label.control-label
        Email
      .controls
        %span.input-xlarge.uneditable-input= @user.email
    .control-group
      %label.control-label
        Телефон
      .controls
        %span.input-xlarge.uneditable-input= @user.phone
    .control-group
      %label.control-label
        Skype
      .controls
        %span.input-xlarge.uneditable-input= @user.skype
    .control-group
      %label.control-label
        Дата рождения
      .controls
        %span.input-xlarge.uneditable-input= @user.formatted_birthday
    .control-group
      %label.control-label
        График работы
      %br
      .controls
        - (1..7).to_a.each do |i|
          %span{:style => "width:100px; display: inline-block;"}= I18n.t('date.day_names')[i]
          %span.input-small.uneditable-input= @user.send("daily_#{i}")
          %br
    .control-group
      %label.control-label
        Менеджер
      .controls
        %span.input-xlarge.uneditable-input
          - if @user.manager
            = @user.manager.full_name
          - else
            \---
    .control-group
      %label.control-label
        Заказчик
      .controls
        %span.input-xlarge.uneditable-input= @user.employer
    .control-group
      %label.control-label
        oDesk аккаунт
      .controls
        %span.input-xlarge.uneditable-input
          = link_to_if(@user.odesk.present?, @user.odesk)
    .control-group
      %label.control-label
        Информация
      .controls
        %span.input-xxlarge.uneditable-input{:readonly => 'readonly', :style => 'height:200px;overflow:auto'}= @user.info.html_safe
      .form-actions
        = link_to admin_users_path, :class => 'btn btn-primary' do
          %i.icon-circle-arrow-left
          Назад
        = link_to edit_admin_user_path, :class => 'btn btn-warning' do
          %i.icon-pencil
          Редактировать